# application.yml

server:
    port: 9000
    
zuul.routes.ledstrip.url: http://localhost:9999/ledstrip
ribbon.eureka.enabled: false   

management:
  security:
    enabled: true


spring:
  resources:
    chain:
      enabled: true  